#生效环境
spring:
  profiles:
      active: dev
  resources:
    static-locations: classpath:/static,classpath:/templates,classpath:/WEB-INF/view/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp


#测试环境
#spring:
#   profiles:
#     active: test
#生产环境
#spring:
#   profiles:
#     active: prod

#配置分页
  pagehelper:
    helper-dialect: mysql  #数据库
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
#隐藏空字段
jackson:
    default-property-inclusion: non_null
