#生效环境
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  profiles:
    active: dev

#测试环境
#spring:
#   profiles:
#     active: test
#生产环境
#spring:
#   profiles:
#     active: prod

#配置分页
  pagehelper:
    helper-dialect: mysql  #数据库
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
#隐藏空字段
jackson:
    default-property-inclusion: non_null
